spring:
    application:
      name:
          
    datasource:
        username: artem
        password: 12345
        url: jdbc:postgresql://localhost:5432/task_management
    jpa:
        hibernate:
            ddl-auto: update
    main:
        banner-mode: off
server:
    port: 9000

management:
    endpoints:
        web:
            exposure:
                include: '*'